### ISSUE TITLE
It's possible to save invalid formats into field "disablebeuser_timeOfInactivityToDisable"

### ISSUE THREAD

**Issue by AMartinNo1** [SvenJuergens/disable_beuser#1]
Yet the message appears that the format is invalid the wrong format is saved anyway.
Setup:
- T3 LTS v7.6.28
- disable_beuser v1.3.2

**Comment by SvenJuergens** [comment]
hi @AMartinNo1 
sorry for the late response, i got no mail about this.
Can you give an example?

**Comment by AMartinNo1** [comment]
I try to find time to reproduce it till sunday
