### ISSUE TITLE
notificationEmail address is used for recipient as well as sender

### ISSUE THREAD

**Issue by moe2k** [SvenJuergens/disable_beuser#3]
Currently the configured notification email addresses are used for the recipient as well as the sender. That does not make too much sense because the sender is not the same as the recipient; thus the notifications will  be treated as spam.

If there was a configuration to set the "from" email separately from the recipient this problem could be solved. If I create a PR would you basically be willing to merge / release a new version?

**Comment by SvenJuergens** [comment]
@moe2k you're right, that's not very good. if you're doing a PR, i can make a new release. with pleasure

**Comment by SvenJuergens** [comment]
@moe2k with v2 the default $GLOBALS['TYPO3_CONF_VARS']['MAIL']['defaultMailFromAddress'] is used, if you need more, you can still send an PR :)

**Comment by moe2k** [comment]
Great, that works for me.
