### ISSUE TITLE
AbstractAdditionalFieldProvider not found

### ISSUE THREAD

**Issue by xQuai** [SvenJuergens/disable_beuser#4]
Hello,

the scheduler task is not working since the latest Update to Version 2.0.0. You can not edit a existing tasks or create a new tasks. My existing disable_be_user task also fails.
The Error from the Log says
`PHP Fatal error:  Class 'TYPO3\\CMS\\Scheduler\\AbstractAdditionalFieldProvider' not found in /var/www/typo3conf/ext/disable_beuser/Classes/Task/DisableBeuserAdditionalFields.php on line 27, referer: http://example.com`

Extension Version: 2.0.0
TYPO3 Version: 8.7.27

Greetings,
xQuai

**Comment by SvenJuergens** [comment]
@xQuai thanks for your feedback.
In fact, I forgot the compatibility with v8. could you be so good and test the current master and see if everything works? then I release a new version :)

**Comment by xQuai** [comment]
I will test it on monday and give you feedback.
Thank you.

**Comment by xQuai** [comment]
@SvenJuergens The current master works now on TYPO3 v8. Thank you for the Update.

**Comment by SvenJuergens** [comment]
@xQuai new Version 2.0.1 is uploaded to ExtensionTer.
Thanks for your feedback :)

**Comment by xQuai** [comment]
@SvenJuergens I still have a note about the update. You use features that are not there yet. The Roadmap of TYPO3 says that Version 8 is compatible with PHP 7.0. I know that PHP 7.0 is out of support, but maybe some people do use it.
The problem is Return Type void. It is a Feature of PHP 7.1 and not available in PHP 7.0.

Example: 
```
<?php
function swap(&$left, &$right): void
{
    if ($left === $right) {
        return;
    }

    $tmp = $left;
    $left = $right;
    $right = $tmp;
}
```

**Comment by SvenJuergens** [comment]
hi @xQuai 
Sorry, php 7.0 has reached End of Life, this version should not be used anymore.
If you still need PHP 7.0 you can still use version 1.3.2 or you can fork the extension and make the necessary customization for yourself. In this case I do not want to downgrade the extension to support an outdated PHP version.

**Comment by xQuai** [comment]
@SvenJuergens I don't use php 7.0, but i read the code and saw the php 7.1 feature.
